name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        proj: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.proj }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.proj }}/package-lock.json
      - run: npm ci || npm i
      - name: Build
        run: |
          if [ "${{ matrix.proj }}" = "backend" ]; then
            npm run build
          else
            npm run build || echo "vite build optional on MVP"
          fi
