name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: vitest (frontend)
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test
      VITE_API_URL: http://localhost:8080
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test